name: OpenAPI Check

on:
  push:
    paths:
      - 'openapi.yaml'
  pull_request:

jobs:
  openapi-check:
    uses: eugenezorkin/openapi-ci-checks/.github/workflows/lint-openapi.yml@main
    with:
      spec_path: openapi.yaml
